Middleware user
ungdev/UA-api pull request #1
Opened 2020-09-17 19:23 UTC by Nathan-Thibault

2020-09-17 22:19 UTC, ThomasLachaux commented on src/middlewares/user.ts
> +      .status(401)
C'est plus une 400 qu'une 401. De plus, on utilise des fonctions de réponse pour éviter la redondance de code. 

Du coup remplacer le bloc `return` par
`return badRequest(res, NotInTeam)` avec la variable `NotInTeam` (à ajouter) une valeur de l'enum `Error`. (Voir fichier `src/types.ts` ligne 169).

2020-09-18 08:37 UTC, ValentinPeltier requested changes

2020-09-18 08:37 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +      .status(401)
Yep, ça devrait être une 400 ici. Tu peux voir ça sur la doc de l'API, par exemple sur cette route : https://ua-api.uttnetgroup.fr/docs/#/Teams/post_teams dans la description y'a marqué "L'utilisateur ne doit pas avoir d'équipe" en italique (et si tu regardes la description toute en haut de la page y'a marqué que les conditions en italique renvoient une 400 si elles ne sont pas respectées).

2020-09-18 08:37 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
`req.body.user.teamId` plutôt parce qu'on va récupérer tout le `user` dans le `body` et donc à partir de l'utilisateur on va pouvoir récupérer l'id de son équipe ;)

2020-09-18 10:45 UTC, Nathan-Thibault commented on src/middlewares/user.ts
> +      .status(401)
Ok super merci je m'occupe de ça.

2020-09-18 10:57 UTC, Nathan-Thibault commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Pour le coup je ne comprends pas trop. Le body ce n'est pas l'user justement ?
```
export interface BodyRequest<T> extends Request {
  body: T;
}
```

2020-09-18 11:03 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Ah si mais du coup faudrait renommer `body` en `user` vu qu'on va stocker que le `user` dedans

2020-09-18 11:08 UTC, Nathan-Thibault commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Parce que là l'interface `BodyRequest<T>` elle utilise ce que moi je connais en java: la généricité (j'ai vérifié que c'était bien le nom sur google). Et du coup dans mon esprit le body ça va être un user `User`.
Alors que si je fais `req.body.user.teamId` je comprends ça comme si il y avait une interface `Body` dans laquelle il y a un user. Et du coup faudrais définir `req` par une `BodyRequest<Body>`.

2020-09-18 11:16 UTC, Nathan-Thibault commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Ah je n'avais pas vu ta réponse du coup j'ai expliqué pourquoi je ne comprenais pas après enfin pas grave.
Du coup autant faire directement une `UserRequest` et supprimé la `BodyRequest<T>` si on ne mettra jamais rien d'autre qu'un user non?

2020-09-18 11:23 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Oui c'est plus propre je trouve

2020-09-18 11:31 UTC, ThomasLachaux commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Euh attendez, le body request est quand même utile, il ne faut pas le supprimer.

2020-09-18 11:32 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Ah oui my bad, ça fait trop longtemps que j'ai pas dev avec express x)
Du coup faut créer un type avec les propriétés `body` et `user`

2020-09-18 11:38 UTC, ThomasLachaux commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Ou encore mieux
```
export interface UserRequest extends Request {
  user: User;
}
export interface UserBodyRequest<T> extends UserRequest { // faut trouver un meilleur nom ^^
  body: T;
}
```

2020-09-18 11:46 UTC, Nathan-Thibault commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
En effet comme ça c'est bien je pense

2020-09-18 12:04 UTC, florianess commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
C'est quoi l’intérêt du T dans  `UserBodyRequest<T>` et de rajouter `body:  T` ? Une request n'a pas déjà un body?

2020-09-18 12:06 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +  if (req.body.teamId) {
Ça permet de spécifier le type du body.
Et non une request n'a pas de body par défaut avec express.js. On utilise une dépendance `body-parser` pour gérer ça, du coup le `.body` n'est pas dans le type `Request`

2020-09-18 12:25 UTC, Nathan-Thibault commented
J'attend que la [PR#2](https://github.com/ungdev/UA-api/pull/2) soit validée pour rebase ensuite car ce qui fait que la CI fail est corrigé dans [ce commit](https://github.com/ungdev/UA-api/commit/5d8efeebb23f30c4dc42972dc5453f4901f682d3#diff-a6e170ee8a99a10f1ac44c478995071f).

2020-09-19 01:17 UTC, ValentinPeltier commented on src/middlewares/user.ts
> +export const isNotInATeam = () => async (req: UserRequest, res: Response, next: NextFunction) => {
Tu peux utiliser une simple fonction ici, pas besoin d'une double (tu peux enlever `() =>` avant `async`)

2020-09-19 11:49 UTC, florianess approved these changes

2020-09-19 12:12 UTC, ThomasLachaux approved these changes

2020-09-19 12:18 UTC, merged