Parameter.ts
ungdev/UA-api pull request #10
Opened 2020-09-28 22:07 UTC by Saperlu

### Que fait la Pull Request ?

- Ajout de 3 middlewares dans src/middlewares/parameters : isCaptainOfTeamId, isUserId, isInTeamId.
- Ajout de fetchTeam() src/operations/team.ts

- Ne pas prendre en compte les changements dans src/controllers : commit de debug par erreur

2020-09-28 22:14 UTC, Saperlu reviewed
Les questions dans la PR plutôt que dans le code

2020-09-28 22:14 UTC, Saperlu commented on src/middlewares/parameters.ts
>      const { userId } = decoded;
Question : Où prendre userId ?
Soit dans le jeton : code redondant
Soit dans la request.user.id mais alors la vérification doit être faite :
 Soit dans chaque route qui utilise isCaptainOfTeamId
 Soit il faut exporter un tableau contenant [isUserId, cette fonction] à la place de isCaptainOfTeamId

2020-09-28 22:14 UTC, Saperlu commented on src/middlewares/parameters.ts
>    return unauthenticated(response);
Je retourne les bonnes erreurs, là ?

2020-09-28 22:14 UTC, Saperlu commented on src/middlewares/parameters.ts
>      if (userId.toString() === captainId) {
Y'a pas moyen d'homogénéiser le type de userId, entre la db, les requêtes, etc... ?
Parce que ça fait utiliser toString() dans tous les sens... Ou alors je fais mal les choses

2020-09-28 22:18 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
>      const { userId } = decoded;
Il faut le prendre dans le token d'autorisation mais je suis d'accord c'est redondant donc tu peux créer un util et rajouter une fonction `getUserId()` par exemple

2020-09-28 22:22 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
>      const { userId } = decoded;
Ce qui me parait le mieux c'est d'utiliser un middleware sur toutes les routes de l'api (donc à appeler dans le fichier src/app.ts) qui vérifierait si la requête a un token d'autorisation et si oui qui récupérerait (fetcherait ça se dit ? :p) toutes les infos de l'utilisateur depuis la DB. Mais ça fait peut être un peu trop de requêtes superflues...

2020-09-28 22:23 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
>      const { userId } = decoded;
@ThomasLachaux @florianess vous en pensez quoi ? On appelle quand le middleware qui fetch l'utilisateur en se basant sur son token ? Sur toutes les routes ou manuellement sur les routes qui en ont besoin ? (j'ai peur qu'on en oublie, même si avec les tests ça devrait le faire, une erreur aussi grosse ça passera pas)

2020-09-28 22:23 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
>    return unauthenticated(response);
Yep c'est tout bon !

2020-09-28 22:44 UTC, ValentinPeltier requested changes
De façon générale, évite de mettre tes questions dans le code ^^ (ou en tout cas ne les push pas)

2020-09-28 22:44 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
>      if (userId.toString() === captainId) {
Y'a un problème de type ici. La ligne où tu appelle `jwt.verify` te retourne une variable de type `Token` (qu'on devrait renommer en `JwtDecoded` ou quelque chose comme ça d'ailleurs). Or le type `Token` n'est pas correct (regarde dans le fichier types.ts, il contient un attribut `userId` de type `number`... ce qui n'est pas normal).
Donc tu peux changer le type `Token` en :
```javascript
export interface Token {
    userId: string;
}
```
(on en profite pour enlever l'attribut `permissions` au passage)
ça devrait résoudre ton problème de `.toString()`, que tu vas pouvoir enlever partout ^^

2020-09-28 22:44 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
> +    if (request.user.teamId === user.teamId) {
Il faut comparer le `teamId` de l'URL (`request.params.teamId`) avec celui qu'on trouve dans la base de données :
```suggestion
    if (request.params.teamId === user.teamId) {
```

2020-09-28 22:44 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
> +    const user = await fetchUser(userId.toString());
Il faudrait vérifier que la fonction renvoie bien un utilisateur avant de passer à la suite

2020-09-28 23:14 UTC, Saperlu commented on src/middlewares/parameters.ts
>      if (userId.toString() === captainId) {
En effet c'est mieux
Par contre, `permission` est utilisé dans `src/middlewares/authentication.ts` : `hasPermission()`

2020-09-28 23:56 UTC, Saperlu commented on src/middlewares/parameters.ts
> +    const user = await fetchUser(userId.toString());
```suggestion
    const user = await fetchUser(userId);
    if (typeof user === User) {
        const { teamId } = user;
        if (request.user.teamId === user.teamId) {
          return next();
        }
    }
    return unauthorized(response);
```
sauf que `typeof user === User` ne fonctionne pas et j'arrive pas à trouver la bonne syntaxe en TypeScript
(`User` importé de `types`)

2020-09-30 15:03 UTC, florianess commented on src/middlewares/parameters.ts
>      const { userId } = decoded;
Oui oui autant mettre ça au départ. Par contre il ne faut le rendre bloquant et continuer meme si pas de token

2020-09-30 17:57 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
>      if (userId.toString() === captainId) {
alors dans `hasPermission()` il faut utiliser `request.user.permissions` à la place de `decoded.permission` (puisqu'on aura utilisé un middleware pour récupérer les informations de l'utilisateur depuis la DB)

2020-10-01 12:46 UTC, ValentinPeltier approved these changes

2020-10-01 12:47 UTC, merged