Settings.ts
ungdev/UA-api pull request #11
Opened 2020-09-29 14:28 UTC by Saperlu

### Que fait la Pull Request ?

-Midlleware : loginAllowed, shopAllowed
-Operation : settings.ts
-Errors : LoginNotAllowed, ShopNotAllowed

2020-09-29 14:32 UTC, Saperlu reviewed
Les questions

2020-09-29 14:32 UTC, Saperlu commented on src/operations/settings.ts
> +};
C'est bon de faire ces fonctions ou c'est plus propre de passer par fetchSetting() ?

2020-09-29 14:32 UTC, Saperlu commented on src/middlewares/settings.ts
> +  if (login === 'true') {
La 2e colonne de settings est un string, ce serait pas mieux de remplacer ça par un booléen vu que settings ne contient que deux champs : `shop` et `login` qui correspondent à des booléens ?

2020-09-29 22:17 UTC, florianess commented on src/operations/settings.ts
> +};
Ça ne me dérange pas comme ça, t'aurai pu 2 en 1 avec une fonction `fetchSetting(setting)` où tu souhaites récupérer le setting en parametre

2020-09-29 22:18 UTC, florianess commented on src/middlewares/settings.ts
> +  if (login === 'true') {
Le truc c'est que BOOLEAN en SQL c'est un TINYINT (1 ou 0) donc après faudra de toute façon le convertir en `true` ou `false` JavaScript

2020-09-30 17:11 UTC, ValentinPeltier commented on src/operations/settings.ts
> +};
Ça me va très bien comme ça. Le but c'est d’abstraire la DB à l'extérieur du dossier `operations` donc une fonction par setting ça me va !

2020-09-30 17:15 UTC, ValentinPeltier commented on src/middlewares/settings.ts
> +  if (login === 'true') {
C'est surtout que lors de la conception de la DB j'ai pensé à la faire le plus modulable possible, c'est à dire qu'on pourra par la suite rajouter d'autres settings, qui contiendront peut être autre chose qu'un booléen (la date d'ouverture des inscriptions par exemple pour l'année prochaine ?)

2020-09-30 18:06 UTC, ValentinPeltier requested changes
Nickel, juste 2-3 petits changements à faire

2020-09-30 18:06 UTC, ValentinPeltier commented on src/types.ts
> +  LoginNotAllowed = "Le login n'est pas autorisé actuellement",
```suggestion
  LoginNotAllowed = "Vous ne pouvez pas vous connecter actuellement",
```

2020-09-30 18:06 UTC, ValentinPeltier commented on src/operations/settings.ts
> +export const fetchSetting = (id: string) => {
Je suis chaud pour enlever cette fonction du coup (voir mon message précédent sur le fait d'abstraire la DB en dehors du dossier `operations`)

2020-09-30 18:06 UTC, ValentinPeltier commented on src/types.ts
> +  ShopNotAllowed = 'Le shop est fermé',
```suggestion
  ShopNotAllowed = 'La billetterie est fermée',
```

2020-09-30 18:09 UTC, ValentinPeltier commented
@Saperlu pense à passer la PR en "ready for review" (en bas de la page, un bouton gris) et à redemander une review (en haut à droite à côté de quelqu'un) pour que ce soit plus rapide et qu'on la merge ;)

2020-10-01 11:42 UTC, ValentinPeltier approved these changes

2020-10-01 11:42 UTC, merged