Middlewares/user.ts init user request()
ungdev/UA-api pull request #18
Opened 2020-10-13 16:26 UTC by Saperlu

### What does the Pull Request ?

- New middleware: initUserRequest()
- Remastered : hasPermissions(), isCaptainOfTeamId(), IsInTeamId()
- Deleted isUserId(), added isUserNull()
- Changed some types : User imported from @prisma, DecodedToken -> new name for Token (also removed permissions from it)

2020-10-15 16:26 UTC, ThomasLachaux approved these changes
Je pense que ça serait cool d'attendre que la #20 soit merge avant de merge la tienne. Mais sinon rien à redire sur ton code selon moi ;)

2020-10-15 16:26 UTC, ThomasLachaux commented on src/middlewares/authentication.ts
>  ): Promise<void> => {
same ici pour l'async. Corrigé avec #20.

2020-10-15 16:26 UTC, ThomasLachaux commented on src/middlewares/parameters.ts
> +    if (request.params.teamId === user.teamId) {
```suggestion
    if (user.teamId === request.params.teamId) {
```
Bon, à ce niveau, c'est du pinaillage ^^

2020-10-15 16:26 UTC, ThomasLachaux commented on src/middlewares/user.ts
>    return next;
```suggestion
  return next();
```
c'est pas tes modifs, mais en passant ^^

2020-10-15 16:26 UTC, ThomasLachaux commented on src/middlewares/authentication.ts
>  export const isAuthenticated = () => async (
C'est pas dans tes modifs, mais il faudra virer l'async ^^. Cf PR #20

2020-10-15 16:26 UTC, ThomasLachaux commented on src/middlewares/authentication.ts
>    response: Response,
same as above

2020-10-15 20:03 UTC, ValentinPeltier requested changes
- Je pense que t'avais mal compris ce que devais faire le middleware `isCaptainOfTeamId`, il faut qu'il vérifie que l'utilisateur est bien le chef de l'équipe désignée par le paramètre `teamId` dans l'URL de la requête et non le chef de sa propre équipe.
- Appelle le middleware `initUserRequest` dans `src/app.ts` pour toutes les routes avec `app.use()` ;)

2020-10-15 20:03 UTC, ValentinPeltier commented on src/types.ts
> -export interface User {
Pourquoi supprimer l'interface `User` et pas les autres ? Je suis d'accord que ça fait redondant avec la définition des tables dans Prisma mais on pourrait utiliser l'héritage pour éviter ça, tout en gardant le type `User` ici puisqu'on va avoir besoin de lui rajouter des propriétés qui ne sont pas dans la DB (comme `hasPaid` qui n'est pas dans la DB mais qu'on peut retourner quand on retourne un utilisateur)

2020-10-15 20:04 UTC, ValentinPeltier commented on src/middlewares/parameters.ts
> +    if (request.params.teamId === user.teamId) {
J'ai pensé pareil mais je me suis dit que c'était logique aussi de comparer le param avec le user ;)

2020-10-15 20:06 UTC, ValentinPeltier commented
Par rapport aux commentaires de @ThomasLachaux je pense qu'on verra une fois que la #20 aura été merge et qu'on aura update cette branche depuis staging, tous les cas seront signalés

2020-10-15 21:08 UTC, ThomasLachaux commented
#20 merge. @Saperlu faudra rebase avec staging ;)

2020-10-25 16:34 UTC, ThomasLachaux commented
@Saperlu évite de faire des merge de staging vers ta branche pour la mettre à jour. Il est préférable de faire des rebase ;)

2020-10-25 16:49 UTC, Saperlu commented on src/middlewares/authentication.ts
> +    if (Number(user.permissions) === permissions || Number(user.permissions) === Permissions.admin) {
Ici, j'ai convertis en Number pour plus avoir l'erreur de type mais je serais pas étonné que ça ne fonctionne pas en test d'intégration. Sauf que j'ai pas compris la nouvelle manière d'utiliser Permission (commit de Valentin d'il y a 2h)

2020-10-26 23:19 UTC, ValentinPeltier approved these changes

2020-10-26 23:22 UTC, merged