fix: added commissions for orga users
ungdev/UA-api pull request #194
Opened 2023-11-17 13:20 UTC by TeddyRoncin

# Add a support to store commissions for each orga

It also allowed for the implementation of the trombi

## Changes

* added field orgaRoles in table users
* added table OrgaRole
* added route GET /users/orgas
* removed user type orga as it was unused
* added permission orga
* added field orgaRoles createFakeUser to specify roles to the created user

2023-11-18 21:45 UTC, DevNono requested changes
Autoriser le fetchOrgas uniquement lorsque le settings trombi est ON

2023-11-18 21:45 UTC, DevNono commented on src/controllers/users/openapi.yml
> +                      member:
Mauvaise indentation

2023-11-19 21:53 UTC, TeddyRoncin commented on src/controllers/users/openapi.yml
> +                      member:
humm, je crois pas

2023-11-20 09:40 UTC, DevNono approved these changes

2023-11-20 14:59 UTC, DevNono requested changes

2023-11-20 14:59 UTC, DevNono commented on src/controllers/users/openapi.yml
> +    summary: Retourne la liste des organisateurs, avec leurs commissions et rôle dans chaque commissions
Euh t'es sûr ?

2023-11-21 14:39 UTC, merged