Merge master
ungdev/UA-api pull request #253
Opened 2024-10-10 17:35 UTC by Suboyyy

# Merge master 

## Changes
DiscordID in the superSearch
Adding some test
Full Custom Badges
Badge images in a volume

2024-10-10 19:57 UTC, tuturd requested changes

2024-10-10 19:57 UTC, tuturd commented on src/utils/env.ts
> +  const DEFAULT_BADGE_VALUE =
Sûr que c'est toujours nécessaire ?
On passe plus par les variables d'environnement il me semble.

2024-10-10 19:57 UTC, tuturd commented on tests/admin/badges/generateBadges.test.ts
>              commissionRole: 'member',
L'attribut commissionRole n'a plus de sens car on passe pas le commissionId par getCommissionName, toujours nécessaire de le mettre dans les tests ?

2024-10-10 20:18 UTC, tuturd commented on src/utils/badge.ts
Line 151 : faudrait essayer avec la couleur foncée de la charte graphique, la couleur claire pour le texte se voit trop mal avec ces badges. 
Code :  `const textFormat = document.font(fontFamily).fill([23, 18, 74]).fontSize(fontSize);`

2024-10-10 20:29 UTC, tuturd commented on src/utils/badge.ts
Il faudrait remonter un peu le nom et prénom pour mieux centrer dans la bande (le commission semble bonne)

2024-10-12 17:40 UTC, Remi-pcn submitted a review, later dismissed

2024-10-12 17:40 UTC, Remi-pcn commented on tests/admin/badges/generateBadges.test.ts
> +            commissionId: 'dev / annimation',
Le test passe quand meme meme si il ya 2 n a animation ?

2024-10-12 17:45 UTC, Suboyyy commented on tests/admin/badges/generateBadges.test.ts
> +            commissionId: 'dev / annimation',
Oui on s'en fout

2024-10-31 21:53 UTC, tuturd submitted a review, later dismissed

2024-11-02 09:48 UTC, Remi-pcn approved these changes

2024-11-02 09:49 UTC, merged